name: Build static files

on:
  workflow_call:
    inputs:
      upload:
        description: "Whether to upload artifact"
        required: false
        type: boolean

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - name: Build assets
        shell: bash
        run: |
          make static
      - uses: actions/upload-artifact@v4
        if: ${{ inputs.upload }}
        with:
          name: static
          path: bin/assets
          retention-days: 1
