name: Publish crate

on:
  workflow_call:
    inputs:
      dir:
        description: "Sub directory"
        required: false
        type: string

jobs:
  publish:
    name: Publish crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Push to crate.io
        run: |
          cd ./${{ inputs.dir }}
          cargo publish --no-verify || true
